apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: xmlx03kzt-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: xmlx03kzt-go 
  name: xmlx03kzt-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: xmlx03kzt-go 
